### ISSUE TITLE
Image links broken 

### ISSUE THREAD

**Issue by lgessler** [fulcrologic/fulcro-developer-guide#28]
E.g. in http://book.fulcrologic.com/fulcro3/#_install_fulcro_inspect, where there is an `<img src="assets/img/inspect-open.png" alt="inspect open">`. Replacing it with `<img src="/assets/img/inspect-open.png" alt="inspect open">` fixes it. Sorry, I'm not sure how to fix it in the `.adoc` file, otherwise I'd submit a PR.

**Comment by awkay** [comment]
Thanks...should be fixed now.

**Comment by awkay** [comment]
Also put in a redirect...v3 is at root now.
