### ISSUE TITLE
There are references to the outdated `reconciler-options` option.

### ISSUE THREAD

**Issue by eihli** [fulcrologic/fulcro-developer-guide#51]
http://book.fulcrologic.com/#SharedState

Looks like `reconciler-options` was removed in the move to version 3. Also, `make-fulcro-client` was changed to `fulcro-app`, I think. I will create a PR when I better understand the change. Maybe it's as simple as renaming `make-fulcro-client` and removing `reconciler-options` and un-nesting the `shared`/`shared-fn`.

**Comment by awkay** [comment]
Fixed. Thanks
