### ISSUE TITLE
Dynamic query parameters example broken

### ISSUE THREAD

**Issue by claesenm** [fulcrologic/fulcro-developer-guide#54]
The example for dynamic queries appears to be broken (example no. 39 -http://book.fulcrologic.com/#DynamicQueries).

**Expected behaviour**: when clicking "_Add :y to query_" the display changes to `y: 99`.
**Actual behaviour**: when clicking "_Add :y to query_" the display remains at `y:` (blank).

**Comment by awkay** [comment]
Yep, and I think exactly zero people are using that feature, which I may have even failed to re-implement in F3. Removed from book.
