### ISSUE TITLE
Your book is not available for purchase on amazon

### ISSUE THREAD

**Issue by dcunited001** [fulcrologic/fulcro-developer-guide#82]
Looks like a fantastic book. it's more more than a clojure-specific take on web-development using a nascent framework ... it seems to be a book that covers the bases for generalist webdevelopment, providing solutions in Fulcro/React/Clojure. (i would like to buy it)

Kudos!

**Comment by awkay** [comment]
Thanks!

Feel free to click on the Sponsor link above if you'd like to send me money :D  

Otherwise, the book is in asciidoc, so feel free to convert it to whatever format you want and read it on an e-reader or print it out.

**Comment by dcunited001** [comment]
@awkay i found the asciidoc-to-PDF functionality very interesting, but i don't know the format is for me. i just recently converted to org, so i'm trying to come up with ways to stay focused on that. but you're doing great work man. 

i couldn't get the asciidoc-pdf gem installed with Ruby on my machine, so the `make` command didn't work for me. the command i needed to run to generate the PDF is below. the process was a snap. however, there were about 4 images that didn't come through. otherwise, having it as a PDF is super helpful.

```shell
docker run -it -v $(pwd):/documents/ asciidoctor/docker-asciidoctor asciidoctor-pdf -o ./docs/DevelopersGuide.pdf -b pdf -r asciidoctor-diagram DevelopersGuide.adoc
```

IMO, for me, fulcro might be a little heavy-handed for some projects, but the idea of having a clojure-based convention-over-configuration framework is super helpful for me. i'm starting a project to do I Ching readings & flashcards. i hope to start with React & API and perhaps build a React Native client as well. this is my first foray into EQL or graph db's, but I'm excited to see if that would fit better than NoSQL/JSON fixtures or SQL.

the projects on this github org will help me a ton in getting into with web development with clojure/script. i cloned all the repos and I'm referring to them in VSCode, with dev in emacs. the last time i dug into web development in clojure was in 2013/2014 and i'm running into a lot of similar problems now: Clojure's one-concern-one-tool "omakase" approach is great, but a bit overwhelming for me because i don't have anyone to ask for advice when i get stuck (i.e. what are the "magic words" i need to google or search for? i have no idea). so having a well-designed framework like Fulcro where all the concerns are satisfied helps a ton.

i don't have enough money to support you just yet, but hopefully sometime soon I can give back. fulcro is a huge undertaking and i don't know why clojure isn't more popular for web-development.
